### ISSUE TITLE
关于FloLPIPS和VFIPS

### ISSUE THREAD

**Issue by Wucy0519** [mulns/VFIBenchmark#1]
您好，感谢您提供测试代码，但是我在运行的代码时，代码要求提供 checkpoint/FloLPIPS.pth 和 checkpoint/VFIPS.pth，我没找到这两个文件，请问可以提供一下嘛

**Comment by WangDongBUAA** [comment]
您好，这两个文件找到了吗，可以提供一下吗

**Comment by Wucy0519** [comment]
有的，兄弟，我放到 https://github.com/Wucy0519/VTinker 的checkpoint文件下面了，flolpips由于有官方的库，直接pip install就行，也欢迎关注我们的工作~ VTinker: Guided Flow Upsampling and Texture Mapping for High-Resolution Video Frame Interpolation

**Comment by Wucy0519** [comment]
如果有别的问题，欢迎随时交流，我的邮箱是: chenyangwu@mail.nankai.edu.cn , 也欢迎了解我们即将开源的CVPR26工作：YOSE: You Only Select Essential Tokens for Efficient DiT-based Video Object Removal

**Comment by WangDongBUAA** [comment]
> 有的，兄弟，我放到 https://github.com/Wucy0519/VTinker 的checkpoint文件下面了，flolpips由于有官方的库，直接pip install就行，也欢迎关注我们的工作~ VTinker: Guided Flow Upsampling and Texture Mapping for High-Resolution Video Frame Interpolation

感谢！👍

**Comment by WangDongBUAA** [comment]
> 如果有别的问题，欢迎随时交流，我的邮箱是: [chenyangwu@mail.nankai.edu.cn](mailto:chenyangwu@mail.nankai.edu.cn) , 也欢迎了解我们即将开源的CVPR26工作：YOSE: You Only Select Essential Tokens for Efficient DiT-based Video Object Removal

好的，谢谢！

**Comment by Wucy0519** [comment]
如果帮到了你，可以点个Star嘛（桃花脸）

**Comment by WangDongBUAA** [comment]
> 如果帮到了你，可以点个Star嘛（桃花脸）

okok
